<?php
namespace AHT\Portfolio\Block\Portfolio;
use Magento\Framework\View\Element\Template;
use Magento\Widget\Block\BlockInterface;
use AHT\Portfolio\Model\ResourceModel\Portfolio\CollectionFactory;

class PortfolioList extends \Magento\Framework\View\Element\Template implements BlockInterface {

    protected $_template = "Widget/portfolio.phtml";
    protected $_portFactory;
    public $_storeManager;

    public function __construct(Template\Context $context, array $data = [], CollectionFactory $portFactory, \Magento\Store\Model\StoreManagerInterface $storeManager)
    {
        $this->_storeManager = $storeManager;
        $this->_portFactory = $portFactory;
        parent::__construct($context, $data);
    }



    public function _beforeToHtml()
    {
        $record = $this->getData("recordofrow");
        $settingColumnImage = $this->getData("settingCountImage");
        $settingMargin = $this->getData("settingMargin");
        $settingAutoPlay = $this->getData("settingAutoPlay");
        $settingLoop = $this->getData("settingLoop");
        $settingNav = $this->getData("settingNav");
        $settingDots = $this->getData("settingDots");
        $model = $this->_portFactory->create();
        $data = $model->setPageSize($record)->getData();
        $this->setData("result", $data);
        $this->setData("settingColumnImage", $settingColumnImage);
        $this->setData("settingMargin", $settingMargin);
        $this->setData("settingAutoPlay", $settingAutoPlay);
        $this->setData("settingLoop", $settingLoop);
        $this->setData("settingNav", $settingNav);
        $this->setData("settingDots", $settingDots);
        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }

    public function getUrlMedia()
    {
        $mediaUrl = $this ->_storeManager-> getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA );
        return $mediaUrl;
    }

    public function urlBase()
    {
        return $this->_baseUrl;
    }


}