<?php
$dataRecord = $this->getData("result");
$urlMedia = $this->getUrlMedia();
$settingColumnImage =  $this->getData("settingColumnImage");
$settingMargin =  $this->getData("settingMargin");
$settingAutoPlay =  $this->getData("settingAutoPlay");
$settingLoop =  $this->getData("settingLoop");
$settingNav =  $this->getData("settingNav");
$settingDots =  $this->getData("settingDots");
?>

<style>
    .portfolio {
        display: inline-block;
        text-align: center;
    }

    .slide-all #slide .item img{
        height: 300px;
    }

    .portfolio .col {
        width: calc(100% / 3);
        float: left;
        box-sizing: border-box;
        padding: 10px;

    }

    .portfolio .col .thumbnail {
        height: 260px;
        overflow: hidden;
    }

    .portfolio .col .thumbnail img {
        width: 100%;
        height: 100%;
    }



</style>

<script>
    (function  () {
        require(["jquery","owlCarousel"],function($) {
            $(document).ready(function(){
                $('#slide').owlCarousel({
                    items : <?php echo  ($settingColumnImage)?>,
                    loop: <?php echo  ($settingLoop == 1) ? '1' : '0'; ?>,
                    margin: <?php echo  $settingMargin; ?>,
                    nav: <?php echo   ($settingNav == 1) ? '1' : '0' ?>,
                    dots: <?php echo   ($settingDots == 1) ? '1' : '0' ?>,
                    autoplay: <?php echo  ($settingAutoPlay == 1) ? '1' : '0' ?>,
                });
            });
        });
    })();

</script>
<div class="slide-all">
    <div class="container-fluid">
        <div class="container slide">
            <div class="owl-carousel owl-theme" id="slide">
                <?php foreach($dataRecord as $value) { ?>
                <div class="item">
                    <img src="<?php echo $urlMedia . "/" . $value["thumbnail"] ?>" class="img-responsive" alt="Image">
                </div>

                <?php  } ?>

            </div>
        </div>
    </div>
</div>


<div class="portfolio">
    <?php foreach ($dataRecord as $key => $value) { ?>
        <div class="col">
            <div class="item thumbnail">
                <img src="<?php echo $urlMedia . "/" . $value["thumbnail"] ?>">
            </div>
            <div class="item">
                <span><a href="<?php echo $block->urlBase() ?>/magento/portfolio/portfolio/show/id/<?php echo $value['id']; ?>"> <?php echo $value["client"] ?></a></span>
            </div>

        </div>
    <?php }?>
</div>